module.exports = {
  showConfig: 'SHOW_CONFIG',
  getInfo: 'GET_INFO',
  listAccounts: 'LIST_ACCOUNTS',
  createAccountName: 'CREATE_ACCOUNT',
  createAccount: 'CREATE_ACCOUNT',
  removeAccount: 'REMOVE_ACCOUNT',
  getAccountInfo: 'ACCOUNT_INFO',
  transfer: 'TRANSFER',
  success: 'SUCCESS',
  ok: 'OK',
  error: 'ERROR',
  balances: 'BALANCES',
  currencyBalances: 'CURRENCY_BALANCES',
  issue: 'ISSUE',
  buyRam: 'BUY_RAM',
  sellRam: 'SELL RAM',
  currencyStats: 'CURRENCY_STATS',
  accountActions: 'ACCOUNT_ACTIONS',
  getTableRows: 'GET_TABLE_ROWS',
  getCode: 'GET_CODE',
  setCode: 'SET_CODE',
  delegateBw: 'DELEGATE_BW',
  yes: 'YES',
  No: 'NO'
}